#- name: Terraform
#  terraform:
#    project_path: ../../example/datastack
#    force_init: true
#    state: present
#  register: terraform
#
#- name: Terraform stdout
#  debug:
#    msg: "{{terraform.stdout}}"